build:
  - changed-files:
    - any-glob-to-any-file: [ CMakeLists.txt, "**/CMakeLists.txt", "**/Makefile", "**/*.cmake", cmake.deps/**/* ]

ci:
  - changed-files:
    - any-glob-to-any-file: [ .github/actions/**, .github/workflows/**, .github/scripts/** ]

clipboard:
  - changed-files:
    - any-glob-to-any-file: [ runtime/autoload/provider/clipboard.vim ]

column:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/sign* ]

diagnostic:
  - changed-files:
    - any-glob-to-any-file: [ runtime/lua/vim/diagnostic.lua ]

diff:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/diff.* ]

documentation:
  - changed-files:
    - any-glob-to-all-files: [ runtime/doc/*, "**/*.md" ]

editorconfig:
  - changed-files:
    - any-glob-to-any-file: [ .editorconfig, runtime/lua/editorconfig.lua, runtime/plugin/editorconfig.lua ]

filetype:
  - changed-files:
    - any-glob-to-any-file: [ runtime/lua/vim/filetype.lua, runtime/lua/vim/filetype/detect.lua ]

folds:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/fold* ]

lsp:
  - changed-files:
    - any-glob-to-any-file: [ runtime/lua/vim/lsp.lua, runtime/lua/vim/lsp/* ]

mouse:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/mouse*Â ]

platform:nix:
  - changed-files:
    - any-glob-to-any-file: [ contrib/flake.lock, contrib/flake.nix ]

snippet:
  - changed-files:
    - any-glob-to-any-file: [ runtime/lua/vim/snippet.lua ]

spell:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/spell* ]

terminal:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/terminal.* ]

test:
  - changed-files:
    - any-glob-to-all-files: [test/**/*]

treesitter:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/lua/treesitter.*, runtime/lua/vim/treesitter.lua, runtime/lua/vim/treesitter/*, runtime/queries/**/* ]

tui:
  - changed-files:
    - any-glob-to-any-file: [ src/nvim/tui/tui.* ]
