name: "news.txt"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
    branches:
    - 'master'
jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'ci:skip-news')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: news.txt needs to be updated
        run: |
          for commit in $(git rev-list HEAD~${{ github.event.pull_request.commits }}..HEAD); do
            message=$(git log -n1 --pretty=format:%s $commit)
            type="$(echo "$message" | sed -E 's|([[:alpha:]]+)(\(.*\))?!?:.*|\1|')"
            breaking="$(echo "$message" | sed -E 's|[[:alpha:]]+(\(.*\))?!:.*|breaking-change|')"
            if [[ "$type" == "feat" ]] || [[ "$type" == "perf" ]] || [[ "$breaking" == "breaking-change" ]]; then
              ! git diff HEAD~${{ github.event.pull_request.commits }}..HEAD --quiet runtime/doc/news.txt ||
              {
                echo "
                  Pull request includes a new feature, performance improvement
                  or a breaking change, but news.txt hasn't been updated yet.
                  This is just a reminder that news.txt may need to be updated.
                  You can ignore this CI failure if you think the change won't
                  be of interest to users."
                  exit 1
               }
            fi
          done
